config/routes.rb
Koshar::Application.routes.draw do
  resources :users
  resources :properties do
    collection { post :import }
  end
  resources :sessions, only: [:new, :create, :destroy]
  
  root to: 'static_pages#home'
  match '/about',       to: 'static_pages#about',     via: 'get'
  match '/listings',    to: 'properties#index',       via: 'get'
  match '/modular',     to: 'static_pages#modular',   via: 'get'
  match '/contact',     to: 'static_pages#contact',   via: 'get'
  match '/import_prop',      to: 'properties#import_prop',      via: 'get'
  match '/upload_images',      to: 'properties#upload_images',      via: 'get'
  match '/signin',      to: 'sessions#new',           via: 'get'
  match '/signout',     to: 'sessions#destroy',       via: 'delete'
  match '/images',      to: 'properities#index', via: 'get'

  match '/jquery',      to: 'properties#jquery',      via: 'get'

  

end

app/models/data_file.rb
class DataFile < ActiveRecord::Base
  def self.save(upload)
    name = upload['datafile'].original_filename
    directory = "/assets/images/"
    path = File.join(directory, name)
    File.open(path, "wb") { |f| f.write(upload['datafile'].read) }
  end
end

app/models/featured_property.rb
class FeaturedProperty < ActiveRecord::Base
  belongs_to :Property
end

app/models/image.rb
class Image < ActiveRecord::Base
  mount_uploader :image, ImgUploader
end

app/models/property.rb
class Property < ActiveRecord::Base
  has_many :Images
  require 'csv'


  def self.import(file)

    Property.destroy_all

    CSV.open("headers.csv", "wb") do |csv|
      csv << %w(MLS status CurrListPrice ListDate StreetAddress StreetName StreetSuffix City State ZIP Area Bedrooms Bathrooms SquareFootage LotSize Remarks YearBuilt Type)

      CSV.foreach(file.path) do |row|
        csv << row
      end
    end

    CSV.foreach("headers.csv", headers: true) do |row|
      Property.create! row.to_hash
    end

    Property.where(:MLS => 0).destroy_all
  end
end

#    CSV.open("headers.csv", "wb") do |csv|
#      csv << %w(test)
#    end



   # arr_of_arrs = CSV.read(file.path)

#    CSV.open(file.path, 'w', :write_headers=> true,
#    :headers => ["MLS", "status", "CurrListPrice", "ListDate", "StreetAddress", "StreetName", "StreetSuffix",
#    "City", "State", "ZIP", "Area", "Bedrooms", "Bathrooms", "SquareFootage", "LotSize", "Remarks", "YearBuilt",
#    "Type"]) do |hdr|
#      hdr << ["MLS, status, CurrListPrice, ListDate, StreetAddress, StreetName, StreetSuffix,
#              City, State, ZIP, Area, Bedrooms, Bathrooms, SquareFootage, LotSize, Remarks, YearBuilt,
#              Type"]
#    end

#   CSV.foreach(file.path, headers: false) do |row|
#      Property.create! row.to_hash
#   end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  
  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :username, presence: true, uniqueness: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }
  
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end
  
  def User.hash(token)
    Digest::SHA1.hexdigest(token.to_s)
  end
  
  private
  
    def create_remember_token
      self.remember_token = User.hash(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  protected
  def logged_in_user
    unless signed_in?
      flash[:danger] = "Please log in."
      redirect_to signin_path
    end
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_filter :logged_in_user, only: [:import_prop, :upload_images]

  def index
    @properties = Property.all
  end

  def show
    @property = Property.find(params[:id])
  end

  def import
    Property.import(params[:file])
    redirect_to properties_path, notice: "Properties imported."
  end

  def destroy
    Property.destroy(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    
  end
  
  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
    else
      flash.now[:error] = 'Invalid username/password combination'
      render 'new'
    end
  end
  
  def destroy
    sign_out
    redirect_to root_url
    
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def listings
  end

  def modular
  end

  def contact
  end
end

app/controllers/upload_controller.rb
class UploadController < ApplicationController
  def index
    render :file => 'app\assets\images\uploadimages.rhtml'
  end
  def uploadImages
    post = DataFile.save(params[:upload])
    render :test => "Images have been uploaded successfully"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "New administrator created successfully!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  private
  
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.hash(remember_token))
    self.current_user = user
  end
  
  def current_user=(user)
    @current_user = user
  end

  def signed_in?
    !current_user.nil?
  end
  
  def current_user
    remember_token = User.hash(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def sign_out
    current_user.update_attribute(:remember_token, User.hash(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/upload_helper.rb
module UploadHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		Koshar Realty, P.C. | 418 East Main St. | P.O. Box 605 | Marcellus, MI 49067
	</br>
		Phone 269-646-5541 | Fax 269-646-2212
	</small>
    <nav>
    	<ul>
          <% if signed_in? %>
            <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
          <% else %>
    	  <li><%= link_to "Sign In", signin_path %></li>
          <% end %>
    	</ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
	 <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "sample app", '#', id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Home",    root_path %></li>
              <li><%= link_to "About",    about_path %></li>
              <li><%= link_to "Listings", listings_path %></li>
              <li><%= link_to "Modular Homes", modular_path %></li>
              <li><%= link_to "Contact Us", contact_path %></li>
              <% if signed_in? %>
              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Admin <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "My Profile", current_user %></li>
                  <li><%= link_to "Import Listings", import_prop_path %></li>
                  <li><%= link_to "Manage Featured", "#" %></li>
                  <li><%= link_to "Manage Properties", "#" %></li>
                  <li><%= link_to "Add User", "#" %></li>
                  <% end %>
                </ul>
              </li>
            </ul>
          </nav>
        </div>
      </div>
    </header>

app/views/layouts/_shim.html.erb
  <!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Koshar Realty | <%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
    	<div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
</body>
</html>

app/views/properties/import_prop.html.erb
<% provide(:title, "Import Listings") %>

<h1>Import Listings</h1>

<%= form_tag import_properties_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "Import CSV" %>
<% end %>

app/views/properties/index.html.erb
<% provide(:title, 'Property Listings') %>
<h1>Property Listings</h1>

<ul class="properties">
  <% @properties.each do |property| %>
    <li>
      <%= link_to image_tag("/assets/#{property.MLS}_1.jpg", :class => "img_preview"), property %>
      <%= link_to property.MLS, property %>
      <%= property.StreetAddress %>
      <%= property.StreetName %>
      <%= property.StreetSuffix %>,
      <%= property.City %>,
      <%= property.State %>
      <%= property.ZIP %>
    </li>
  <% end %>
</ul>

app/views/properties/jquery.html.erb
<!DOCTYPE HTML>
<html xmlns="http://www.w3.org/1999/html">
<head>
  <meta charset="utf-8">
  <title>jQuery File Upload Example</title>
</head>
<body>
<input id="fileupload" type="file" name="files[]" data-url="server/php/" multiple>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="js/vendor/jquery.ui.widget.js"></script>
<script src="js/jquery.iframe-transport.js"></script>
<script src="js/jquery.fileupload.js"></script>
<script>
    $(function () {
        $('#fileupload').fileupload({
            dataType: 'json',
            done: function (e, data) {
                $.each(data.result.files, function (index, file) {
                    $('<p/>').text(file.name).appendTo(document.body);
                });
            }
        });
    });
</script>
<script>
$(function () {
$('#fileupload').fileupload({
dataType: 'json',
add: function (e, data) {
data.context = $('<button/>').text('Upload')
.appendTo(document.body)
.click(function () {
data.context = $('<p/>').text('Uploading...').replaceAll($(this));
data.submit();
});
},
done: function (e, data) {
data.context.text('Upload finished.');
}
});
});
</script>
</body>
</html>

app/views/properties/show.html.erb
<% provide(:title, @property.MLS.to_s) %>

<h1>MLS #<%= @property.MLS %></h1>
<h2><%= @property.StreetAddress %>
    <%= @property.StreetName %>
    <%= @property.StreetSuffix %>,
    <%= @property.City %>,
    <%= @property.State %></h2>

app/views/properties/upload_images.html.erb
<% provide(:title, "Upload Images") %>

<h1>Upload Images</h1>


<%= form_for Image.new, :html => {:multipart => true} do |f| %>
   <p>
     <%= f.file_field :image %>
  </p>
    <%= f.submit %>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About Koshar Realty, P.C.</h1>
<p>Koshar Realty has been operating in Marcellus, Michigan since April 1971. We specialize in buying and selling residential, commercial, and lakefront properties in Cass County, St. Joseph County, and Van Buran County. We also handle farm acreage, vacant lots, and manufactured housing.</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>

<h1>Welcome to Koshar Realty</h1>
<p>Whether you are ready to settle into that ideal home for you and your family, looking for a perfect spot to build a new home, or need space to embark on a new business venture, Koshar Realty is here to help you meet your real estate needs.

We'd like to help you get started today, so click here to view all of our current listings, or visit our contact page to let us know what you're looking for and we will personalize some potential matches for you!</p>

app/views/static_pages/listings.html.erb
<% provide(:title, 'Listings') %>
<h1>StaticPages#listings</h1>
<p>Find me in app/views/static_pages/listings.html.erb</p>

app/views/static_pages/modular.html.erb
<% provide(:title, 'Modular Homes') %>
<h1>StaticPages#modular</h1>
<p>Find me in app/views/static_pages/modular.html.erb</p>

app/views/users/show.html.erb
<% provide(:title, 'User Profile') %>

<h1>Welcome, <%= @user.firstname %>!</h1>
<%= @user.firstname %> <%= @user.lastname %><br />
<%= @user.username %><br />
<%= @user.email %>